imprints

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -4,41 +4,38 @@ on:
   push:
     branches:
       - infra
+  pull_request:
 
 jobs:
   checkov_scan:
-    name: Run Checkov on Kubernetes Manifests
+    name: Run Checkov on Terraform Code
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Set up Docker
-        uses: docker/setup-buildx-action@v3
-
-      - name: List Terraform files
-        run: |
-          echo "Terraform files found:"
-          find terraform -type f -name "*.tf"
-
-
       - name: Run Checkov scan
         run: |
-          echo "Running Checkov scan in Docker container"
+          echo "Running Checkov scan..."
           docker run --rm \
             --entrypoint "" \
             -v ${{ github.workspace }}:/repo \
             -w /repo \
             -e BC_SKIP_MAPPING=true \
             bridgecrew/checkov:3.2.447 \
-            checkov -d terraform/ --framework terraform --skip-download --skip-results-upload --compact -o json > full_checkov_output.json || true
+            checkov -d terraform/ \
+              --framework terraform \
+              --download-external-modules all \
+              --var-file terraform/variables.tf \
+              -o json > full_checkov_output.json || true
 
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
 
-      - name: Parse and print failed checks
+      - name: Print failed checks
         run: |
+          echo "===== FAILED CHECKS ====="
           jq -r '
             .results.failed_checks[]?
             | select(.check_result.result == "FAILED")
@@ -46,13 +43,11 @@ jobs:
           ' full_checkov_output.json || echo "No failed checks found."
 
           echo "===== SUMMARY ====="
-          jq -r '.summary' full_checkov_output.json
-          cat full_checkov_output.json
+          jq -r '.summary // "No summary found"' full_checkov_output.json
 
       - name: Upload Checkov output
         uses: actions/upload-artifact@v4
         with:
           name: checkov-results
-          path: |
-            full_checkov_output.json
+          path: full_checkov_output.json
           retention-days: 7
